export const NEWS_LIST_ACTION_TYPE = {
    NEWS_LIST_BOARD_UPLOAD_PENDING: 'LOGIN_ACTION_TYPE.NEWS_LIST_BOARD_UPLOAD_PENDING',
    NEWS_LIST_BOARD_UPLOAD_SUCCESS: 'LOGIN_ACTION_TYPE.NEWS_LIST_BOARD_UPLOAD_SUCCESS',
    NEWS_LIST_BOARD_UPLOAD_ERROR: 'LOGIN_ACTION_TYPE.NEWS_LIST_BOARD_UPLOAD_ERROR',
  };
   